version: '3'
services:
  dev:
    container_name: carpark
    image: carpark:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
